---
title: "SeylerHyyppa_FinalProject_dataexploration"
author: "Meghan Seyler"
date: "4/3/2022"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r include=FALSE, warning = FALSE}
#examine working directory
getwd()

#loading packages for exploratory analysis 
library(tidyverse)
library(sf)
library(leaflet)
library(mapview)
library(RColorBrewer)
library(dplyr)
library(knitr)
library(ggplot2)
```

# 3 Exploratory Analysis
(Rubric: flow between text and visualization is cohesive & relevant exploratory information is visualized)

mapview resource https://r-spatial.github.io/mapview/articles/articles/mapview_02-advanced.html

```{r explore counties data}
#
colnames(counties_sf)

#
st_crs(counties_sf) 

#
nrow(counties_sf)

#Reveal the extent of this dataset via the st_bbox() function
st_bbox(counties_sf)

#View the data
head(counties_sf)
```


```{r explore svi data}
#select columns of interest from SVI data
svi2018_nc_raw <- read.csv(
  'https://svi.cdc.gov/Documents/Data/2018_SVI_Data/CSV/States_Counties/NorthCarolina_COUNTY.csv',
  colClasses = c('FIPS' = 'factor')) %>% 
  select(COUNTY, FIPS, LOCATION, E_TOTPOP, E_POV, E_MINRTY)

#check structure
str(svi2018_nc_raw)

#check colnames
colnames(svi2018_nc_raw)

#investigate what location column includes
glimpse(svi2018_nc_raw$LOCATION)

#total poverty and minority statistics by county
povdividedbytotal_col<-(svi2018_nc_raw$E_POV/svi2018_nc_raw$E_TOTPOP)*100

minrtydividedbytotal_col<-(svi2018_nc_raw$E_MINRTY/svi2018_nc_raw$E_TOTPOP)*100

svi2018_nc_processed<-svi2018_nc_raw%>%
  add_column(Percent_POV = povdividedbytotal_col)%>%
  add_column(Percent_MINRTY = minrtydividedbytotal_col)

svi2018_nc_poverty_top10 <- svi2018_nc_processed %>%
    group_by(COUNTY) %>%
    top_n(10, Percent_POV)
    
svi2018_nc_poverty_top10 <- svi2018_nc_processed %>%
    arrange(desc(Percent_POV))%>%
    slice(1:10)%>%
    relocate(Percent_POV, .before = FIPS)

svi2018_nc_minrty_top10 <- svi2018_nc_processed %>%
    arrange(desc(Percent_MINRTY))%>%
    slice(1:10)%>%
   relocate(Percent_MINRTY, .before = FIPS)

```

```{r summary of top MINRTY and POV counties}
knitr::kable(head(svi2018_nc_poverty_top10[1:10,1:2]), 
             "simple", 
             col.names = c("County","Poverty Percentage"),
             align = 'c',
             caption = "The Ten Counties with the Highest Poverty Percentage in North Carolina"
)

knitr::kable(head(svi2018_nc_minrty_top10[1:10,1:2]), 
             "simple", 
             col.names = c("County","Minority Percentage"),
             align = 'c',
             caption = "The Ten Counties with the Highest Percentage of Minority Populations in North Carolina"
) 
```

```{r exploration plots}
poverty_plot<- minority_plot<-svi2018_nc_processed%>%
  arrange(Percent_POV)%>%
  mutate(COUNTY=factor(COUNTY, COUNTY))%>%
    ggplot(aes(x=COUNTY, y=Percent_POV)) +
      geom_point(color="lightgreen") + 
      geom_segment( aes(x=COUNTY, xend=COUNTY, y=0, yend=Percent_POV))+
      coord_flip()+
      ggtitle("Percentage of Poverty by County in North Carolina")
      xlab("County Name")+
      ylab("Poverty Population Percentage")+
      ggsubtitle("By Reino Hyyppa and Meghan Seyler")
      theme_minimal()
      theme(
        panel.grid.major.y = element_blank(),
        panel.border = element_blank(),
        axis.ticks.y = element_blank(),
  )

poverty_plot

minority_plot<-svi2018_nc_processed%>%
  arrange(Percent_MINRTY)%>%
  mutate(COUNTY=factor(COUNTY, COUNTY))%>%
    ggplot(aes(x=COUNTY, y=Percent_MINRTY)) +
      geom_point(color="69b3a2") + 
      geom_segment( aes(x=COUNTY, xend=COUNTY, y=0, yend=Percent_MINRTY))+
      coord_flip()+
      ggtitle("Percentage of Minority Populations by County in North Carolina")
      xlab("County Name")+
      ylab("Minority Population Percentage")+
      theme_minimal()
      theme(
        panel.grid.major.y = element_blank(),
        panel.border = element_blank(),
        axis.ticks.y = element_blank(),
        plot.subtitle = element_text("By Reino Hyyppa and Meghan Seyler"),
  )
      
minority_plot

```







