---
title: "SeylerHyyppa_FinalProject_dataanalysis"
author: "Meghan Seyler"
date: "4/3/2022"
output: html_document
editor_options: 
  chunk_output_type: console
---

# 4 Analysis 


```{r analyze data}

landfill_sites <- read.csv("../ENV872-SeylerHyyppa_Final/Data/Processed/SW_FacilityList_processed.csv", stringsAsFactors = TRUE)

head(landfill_sites)
dim(landfill_sites)

#Convert to a spatial dataframe
landfill_sites_sf <- landfill_sites %>% 
  st_as_sf(coords = c('long','lat'),
           crs=4326)

landfill_sf_utm <- st_transform(landfill_sites_sf, crs = 26917)

# view using ggplot
ggplot(data = landfill_sites_sf) + geom_sf()

#View using mapview
mapview(landfill_sites_sf)

```


# 5 Visualization
```{r join.attributes.to.spatial features county level}

#View minortiy and poverty counts with mapview
mapview(counties_sf_svi_processed, 
        zcol = 'E_POV', 
        col.regions = brewer.pal(2, 'RdBu')) + 
  mapview(landfill_sites_sf, cex = 3, col.regions="green")

mapview(counties_sf_svi_processed, 
        zcol = 'E_MINRTY', 
        col.regions = brewer.pal(2, 'RdBu')) + 
  mapview(landfill_sites_sf, cex = 3, col.regions="green")

#view minority and poverty percentages with mapview
mapview(counties_sf_svi_processed, 
        zcol = 'Percent_POV', 
        col.regions = brewer.pal(2, 'RdBu')) + 
  mapview(landfill_sites_sf, cex = 3, col.regions="green")

mapview(counties_sf_svi_processed, 
        zcol = 'Percent_MINRTY', 
        col.regions = brewer.pal(2, 'RdBu')) + 
  mapview(landfill_sites_sf, cex = 3, col.regions="green")

```

```{r join.attributes.to.spatial features tract level}

#View minortiy and poverty counts with mapview
mapview(svi2018_nc_tract_st, 
        zcol = 'E_POV', 
        col.regions = brewer.pal(2, 'RdBu')) + 
  mapview(landfill_sites_sf, cex = 3, col.regions="green")

mapview(svi2018_nc_tract_st, 
        zcol = 'E_MINRTY', 
        col.regions = brewer.pal(2, 'RdBu')) + 
  mapview(landfill_sites_sf, cex = 3, col.regions="green")

#view minority and poverty percentages with mapview
mapview(svi2018_nc_tract_st, 
        zcol = 'Percent_POV', 
        col.regions = brewer.pal(2, 'RdBu')) + 
  mapview(landfill_sites_sf, cex = 3, col.regions="green", alpha = 1)

mapview(svi2018_nc_tract_st, 
        zcol = 'Percent_MINRTY', 
        col.regions = brewer.pal(2, 'RdBu')) + 
  mapview(landfill_sites_sf, cex = 3, col.regions="green")
```

```{r linear model}

#Convert to UTM Zone 17 (crs = 26917)
svi2018_tract_utm <- st_transform(svi2018_nc_tract_st, crs = 26917)
landfill_utm <- st_transform(landfill_sites_sf, crs = 26917)

# identify census tract centroids using st_centroid function
tract_centroids <- st_centroid(svi2018_tract_utm)
mapview(tract_centroids) 

# install packages for nearest neighbor calculation
#install.packages('nngeo')
library(nngeo)

# identify nearest landfill to each tract centroid and calculate distance
landfill_nn <- st_nn(x=tract_centroids, y=landfill_utm, returnDist = TRUE, k = 1) %>% 
  set_names("Site", "Distance") %>% 
  map_df(., unlist)

# combine centroid-landfill distances with SVI data set 
svi2018_nc_tract_st <- cbind(svi2018_nc_tract_st, landfill_nn)

# linear model for low-income population and distance to landfill
pov_regression <- lm(data = svi2018_nc_tract_st, Distance ~ Percent_POV)
summary(pov_regression)


# linear model for minority populations and distance to landfill 
min_regression <- lm(data = svi2018_nc_tract_st, Distance ~ Percent_MINRTY)
summary(min_regression)

# check diagnostic plots
par(mfrow = c(1,1))
plot(min_regression)

# remove outlier (interestingly all the outliers are from the same county)
inx.o <- c(342, 341, 340, 339, 338, 337)
m2_out <- with(svi2018_nc_tract_st[-inx.o, ], lm(Distance~Percent_MINRTY))

# removing outliers did not meet the assumptions of the model
par(mfrow=c(1,1))
plot(m2_out)

# log transform social vulnerability data
svi2018_nc_tract_st <- 
  mutate(svi2018_nc_tract_st, log_min = log(svi2018_nc_tract_st$Percent_MINRTY),
         svi2018_nc_tract_st, log_pov = log(svi2018_nc_tract_st$Percent_POV))

# run linear model on log transformed minority data
logMin_regression <- lm(data = svi2018_nc_tract_st, Distance ~ log_min)
summary(min_regression)

# try to remove any NAs
svi2018_nc_tract_st <- na.omit(svi2018_nc_tract_st) 

# rerun the model

logMin_regression2 <- lm(data = svi2018_nc_tract_st, Distance ~ log_min)
summary(logMin_regression2)

# Test for correlation using the Kendall Rank correlation test
cor.test(svi2018_nc_tract_st$Percent_MINRTY, svi2018_nc_tract_st$Distance, method = "kendall")
cor.test(svi2018_nc_tract_st$Percent_POV, svi2018_nc_tract_st$Distance, method = "kendall")
```

```{r plot data}
ggplot(svi2018_nc_tract_st, aes(Percent_MINRTY, Percent_POV, size = Distance)) +
  geom_point(alpha = 0.5)
```

# 6 Summary and Conclusions


To Do: 
# Shorten name of counties_sf_svi_processed
# change size of landfill bubbles
# st_intersects() to return list of 
